import os
import re

QUIZZES = {
    1: [
        {"question_text": "Which of the following describes the correct order of C compilation stages?", "options": ["Preprocessing, Compilation, Assembly, Linking", "Compilation, Assembly, Linking, Preprocessing", "Preprocessing, Linking, Compilation, Assembly", "Linking, Preprocessing, Compilation, Assembly"], "correct_answer": "Preprocessing, Compilation, Assembly, Linking", "explanation": "The C compiler pipeline strictly follows: preprocessing (expanding macros), compilation (to assembly), assembly (to machine code), and linking (combining objects into executable).", "difficulty": "Medium"},
        {"question_text": "What is the primary role of the linker in the C compilation process?", "options": ["To check for syntax errors", "To convert assembly code into machine code", "To combine multiple object files and resolve library references into a single executable", "To expand #include directives"], "correct_answer": "To combine multiple object files and resolve library references into a single executable", "explanation": "The linker resolves external symbol references across multiple object files and links standard libraries to produce the final executable binary.", "difficulty": "Medium"},
        {"question_text": "What does a non-zero return value from the main() function indicate to the operating system?", "options": ["Successful execution", "An execution error or abnormal termination", "The program is waiting for user input", "Memory leak detected"], "correct_answer": "An execution error or abnormal termination", "explanation": "By convention, return 0 indicates success, while any non-zero value indicates that an error occurred during execution.", "difficulty": "Beginner"},
        {"question_text": "What happens during the preprocessing stage?", "options": ["Source code is converted to machine code", "Syntax errors are detected", "Macros are expanded and header files are included directly into the source code", "The executable is generated"], "correct_answer": "Macros are expanded and header files are included directly into the source code", "explanation": "The preprocessor handles directives like #include and #define before the actual compiler even sees the code.", "difficulty": "Beginner"},
        {"question_text": "Which tool translates C source code into assembly language?", "options": ["Preprocessor", "Compiler", "Assembler", "Linker"], "correct_answer": "Compiler", "explanation": "The compiler specifically translates high-level C code into low-level assembly instructions specific to the target CPU architecture.", "difficulty": "Beginner"},
        {"question_text": "What is the purpose of the #include <stdio.h> directive?", "options": ["To define the main function", "To include standard input/output function declarations like printf and scanf", "To link the math library", "To compile the program"], "correct_answer": "To include standard input/output function declarations like printf and scanf", "explanation": "stdio.h contains the declarations for standard I/O functions, allowing the compiler to verify their usage before linking.", "difficulty": "Beginner"},
        {"question_text": "What is the difference between a syntax error and a compile error?", "options": ["Syntax errors happen at runtime, compile errors happen before execution", "Syntax errors are caused by invalid C grammar; compile errors include syntax errors but can also involve type mismatches", "They are exactly the same thing", "Syntax errors only happen in the linker"], "correct_answer": "Syntax errors are caused by invalid C grammar; compile errors include syntax errors but can also involve type mismatches", "explanation": "Syntax errors (e.g., missing semicolons) are a subset of compile errors. Compile errors can also occur from invalid types or missing declarations.", "difficulty": "Medium"},
        {"question_text": "What is an object file (.o or .obj)?", "options": ["A plain text file containing C code", "The final executable that can be run", "Compiled machine code for a single source file, not yet linked into an executable", "A file containing preprocessor macros"], "correct_answer": "Compiled machine code for a single source file, not yet linked into an executable", "explanation": "Object files contain machine code but still have unresolved references to external functions, which the linker will resolve later.", "difficulty": "Medium"}
    ],
    2: [
        {"question_text": "What determines the size of an int variable in C?", "options": ["It is always 4 bytes", "It depends on the compiler and target architecture", "It is always 8 bytes", "It depends on the value assigned to it"], "correct_answer": "It depends on the compiler and target architecture", "explanation": "The C standard guarantees an int is at least 16 bits, but it is typically 32 bits (4 bytes) on modern architectures, depending on the compiler.", "difficulty": "Medium"},
        {"question_text": "Which format specifier is used to print a double precision floating-point number?", "options": ["%d", "%f", "%lf", "%c"], "correct_answer": "%lf", "explanation": "%lf is used in scanf for double, and while %f works in printf for double (due to promotion), %lf explicitly denotes a long float (double).", "difficulty": "Beginner"},
        {"question_text": "What is the purpose of the 'const' keyword?", "options": ["To declare a variable whose value cannot be changed after initialization", "To make a variable accessible globally", "To allocate memory on the heap", "To increase execution speed"], "correct_answer": "To declare a variable whose value cannot be changed after initialization", "explanation": "const prevents reassignment of a variable, ensuring read-only behavior throughout its scope.", "difficulty": "Beginner"},
        {"question_text": "What happens if you assign a floating-point value to an integer variable (e.g., int x = 3.14)?", "options": ["The compiler throws an error", "The value is rounded to the nearest integer (3)", "The fractional part is truncated, storing just the whole number (3)", "The variable type dynamically changes to float"], "correct_answer": "The fractional part is truncated, storing just the whole number (3)", "explanation": "C performs implicit type conversion, truncating (dropping) the decimal portion without rounding.", "difficulty": "Medium"},
        {"question_text": "What is the range of a standard signed 8-bit char?", "options": ["0 to 255", "-128 to 127", "-256 to 255", "0 to 127"], "correct_answer": "-128 to 127", "explanation": "A signed 8-bit integer uses one bit for the sign, leaving 7 bits for the magnitude, spanning from -128 to 127.", "difficulty": "Hard"},
        {"question_text": "Which of the following is a valid C variable name?", "options": ["1st_number", "first-number", "_first_number", "first number"], "correct_answer": "_first_number", "explanation": "Variable names can contain letters, numbers, and underscores, but cannot start with a number or contain spaces/hyphens.", "difficulty": "Beginner"},
        {"question_text": "What is the result of sizeof(char) in C?", "options": ["It depends on the architecture", "Exactly 1", "Exactly 2", "Exactly 4"], "correct_answer": "Exactly 1", "explanation": "The C standard explicitly defines sizeof(char) to be exactly 1 byte across all architectures.", "difficulty": "Medium"},
        {"question_text": "Which data type is most appropriate to store the population of the entire world (approx 8 billion)?", "options": ["int", "long", "long long", "float"], "correct_answer": "long long", "explanation": "A standard 32-bit int maxes out at ~2.1 billion. A 64-bit long long safely holds up to ~9 quintillion.", "difficulty": "Hard"}
    ],
    3: [
        {"question_text": "What is the result of the expression 5 / 2 in C?", "options": ["2.5", "2", "3", "Error"], "correct_answer": "2", "explanation": "When both operands are integers, C performs integer division, which truncates the fractional part.", "difficulty": "Beginner"},
        {"question_text": "What does the modulo operator '%' do?", "options": ["Calculates percentage", "Performs integer division", "Returns the remainder of integer division", "Raises a number to a power"], "correct_answer": "Returns the remainder of integer division", "explanation": "The % operator computes the remainder when the first integer is divided by the second (e.g., 5 % 2 = 1).", "difficulty": "Beginner"},
        {"question_text": "What is the difference between prefix (++i) and postfix (i++) increment?", "options": ["There is no difference", "Prefix increments first then returns the value; postfix returns the original value then increments", "Postfix increments first then returns the value; prefix returns the original value then increments", "Prefix is used for integers, postfix for floats"], "correct_answer": "Prefix increments first then returns the value; postfix returns the original value then increments", "explanation": "Prefix evaluates to the new incremented value immediately. Postfix evaluates to the old value before incrementing.", "difficulty": "Medium"},
        {"question_text": "What will printf(\"%5d\", 12) output?", "options": ["12000", "00012", "   12", "12   "], "correct_answer": "   12", "explanation": "The %5d format specifies a minimum width of 5 characters, right-aligned, padded with spaces on the left.", "difficulty": "Medium"},
        {"question_text": "What is required before using scanf() to read into a standard integer variable `int x`?", "options": ["The variable must be initialized to 0", "You must pass the variable's memory address using the & operator", "You must cast the variable to a string", "You must allocate heap memory"], "correct_answer": "You must pass the variable's memory address using the & operator", "explanation": "scanf needs the memory address (&x) to directly write the read value into the variable's memory location.", "difficulty": "Beginner"},
        {"question_text": "Which operator has the highest precedence?", "options": ["Assignment (=)", "Addition (+)", "Multiplication (*)", "Logical AND (&&)"], "correct_answer": "Multiplication (*)", "explanation": "Multiplication (*) has higher precedence than addition (+), logical AND (&&), and assignment (=).", "difficulty": "Beginner"},
        {"question_text": "What is the result of the bitwise XOR expression `5 ^ 3` (binary 0101 ^ 0011)?", "options": ["6", "2", "7", "1"], "correct_answer": "6", "explanation": "XOR compares bits: 0101 ^ 0011 = 0110 (decimal 6). Bits are 1 if they differ, 0 if they are the same.", "difficulty": "Hard"},
        {"question_text": "What is short-circuit evaluation in logical operators?", "options": ["The compiler removes unused variables", "Logical expressions stop evaluating as soon as the final result is determined", "The program crashes if a boolean condition is too complex", "Division by zero bypasses the operation"], "correct_answer": "Logical expressions stop evaluating as soon as the final result is determined", "explanation": "In an expression like (A && B), if A is false, B is never evaluated because the entire expression is already guaranteed to be false.", "difficulty": "Hard"}
    ],
    4: [
        {"question_text": "What is the correct syntax for an 'if-else if' statement?", "options": ["if (cond) { } elseif (cond) { }", "if (cond) { } else if (cond) { }", "if (cond) { } elif (cond) { }", "if cond { } else if cond { }"], "correct_answer": "if (cond) { } else if (cond) { }", "explanation": "C requires space between else and if, and conditions must be enclosed in parentheses.", "difficulty": "Beginner"},
        {"question_text": "What does a 'switch' statement require for each case to prevent fall-through?", "options": ["A continue statement", "A return statement", "A break statement", "A semicolon"], "correct_answer": "A break statement", "explanation": "Without a break statement, execution will 'fall through' and execute the code for subsequent cases.", "difficulty": "Beginner"},
        {"question_text": "Which operator evaluates a condition inline as a shorthand for if-else?", "options": ["Bitwise OR (|)", "Ternary operator (? :)", "Logical AND (&&)", "Switch operator (->)"], "correct_answer": "Ternary operator (? :)", "explanation": "The ternary operator (condition ? true_val : false_val) evaluates inline, returning one of two values.", "difficulty": "Medium"},
        {"question_text": "What happens if a switch expression evaluates to a value not explicitly handled by any 'case'?", "options": ["The program crashes", "The compiler throws an error", "Execution jumps to the 'default' case if provided, otherwise the block is skipped", "The first case is executed by default"], "correct_answer": "Execution jumps to the 'default' case if provided, otherwise the block is skipped", "explanation": "The default case acts as a fallback for unhandled values. If it's missing, the switch block is safely bypassed.", "difficulty": "Beginner"},
        {"question_text": "In C, what integer value represents 'true' in a boolean condition?", "options": ["Only 1", "Only -1", "Any non-zero value", "Any positive value"], "correct_answer": "Any non-zero value", "explanation": "C natively treats 0 as false and absolutely any non-zero value (positive or negative) as true.", "difficulty": "Medium"},
        {"question_text": "Can a switch statement evaluate a string variable (char array) in C?", "options": ["Yes, using strcmp internally", "Yes, natively", "No, switch statements in C only evaluate integer and character constant expressions", "No, unless cast to a double"], "correct_answer": "No, switch statements in C only evaluate integer and character constant expressions", "explanation": "C's switch statement strictly evaluates integral types (char, int, enum) against compile-time constants. It cannot evaluate strings.", "difficulty": "Hard"},
        {"question_text": "What is a common pitfall involving the assignment operator in if statements, e.g., if(x = 5)?", "options": ["It compares x to 5", "It causes a syntax error", "It assigns 5 to x and evaluates as true, ignoring the original value of x", "It checks if x was previously assigned"], "correct_answer": "It assigns 5 to x and evaluates as true, ignoring the original value of x", "explanation": "The single = is assignment, not comparison (==). The assignment evaluates to 5, which is non-zero (true).", "difficulty": "Hard"},
        {"question_text": "Is the 'else' block mandatory in an if statement?", "options": ["Yes", "No", "Only if there is no break statement", "Only if returning a value"], "correct_answer": "No", "explanation": "An 'if' block can stand alone. The 'else' block is completely optional.", "difficulty": "Beginner"}
    ],
    5: [
        {"question_text": "What is the main difference between a while loop and a do-while loop?", "options": ["A while loop uses less memory", "A do-while loop guarantees the loop body executes at least once", "A while loop is faster", "A do-while loop cannot use a break statement"], "correct_answer": "A do-while loop guarantees the loop body executes at least once", "explanation": "Because a do-while loop evaluates its condition at the bottom of the loop, the block always runs at least one time.", "difficulty": "Beginner"},
        {"question_text": "Which looping construct is specifically designed for iterating a known, fixed number of times?", "options": ["while loop", "do-while loop", "for loop", "goto loop"], "correct_answer": "for loop", "explanation": "A for loop encapsulates initialization, condition checking, and incrementing in a single line, making it ideal for fixed-count iterations.", "difficulty": "Beginner"},
        {"question_text": "What does the 'continue' statement do inside a loop?", "options": ["Exits the entire loop immediately", "Skips the rest of the current iteration and immediately evaluates the loop condition for the next iteration", "Pauses execution for user input", "Jumps to the beginning of the program"], "correct_answer": "Skips the rest of the current iteration and immediately evaluates the loop condition for the next iteration", "explanation": "Unlike 'break' which exits the loop entirely, 'continue' just aborts the current pass and advances to the next one.", "difficulty": "Medium"},
        {"question_text": "What happens if a loop condition evaluates to true endlessly (e.g., while(1))?", "options": ["The compiler catches the error and refuses to compile", "The program executes exactly 1000 times and then crashes", "An infinite loop occurs, executing until manually terminated or interrupted by the OS", "The loop is bypassed entirely"], "correct_answer": "An infinite loop occurs, executing until manually terminated or interrupted by the OS", "explanation": "C will happily execute an infinite loop forever unless a break statement is hit or external forces kill the process.", "difficulty": "Beginner"},
        {"question_text": "In a for loop: `for(init; cond; inc)`, when is the `inc` (increment) section executed?", "options": ["Before the loop condition is checked for the very first time", "At the very end of each iteration, after the loop body has executed", "At the very beginning of the loop body", "Only when the condition evaluates to false"], "correct_answer": "At the very end of each iteration, after the loop body has executed", "explanation": "The loop runs its body, then executes the increment expression, and finally re-evaluates the condition.", "difficulty": "Medium"},
        {"question_text": "Can you declare a variable inside the initialization statement of a C99 for loop?", "options": ["Yes, e.g., for(int i=0; i<5; i++)", "No, variables must always be declared at the top of the function", "Only if it is a float", "Only if you include <stdlib.h>"], "correct_answer": "Yes, e.g., for(int i=0; i<5; i++)", "explanation": "Since the C99 standard, loop-scoped variable declarations inside the for loop init block are natively supported.", "difficulty": "Medium"},
        {"question_text": "What is the output of this loop: `for(int i=0; i<3; i++) { if(i==1) break; printf(\"%d\", i); }`", "options": ["012", "0", "1", "01"], "correct_answer": "0", "explanation": "The loop prints 0, then on the next iteration i=1, the break statement immediately terminates the entire loop before printing.", "difficulty": "Hard"},
        {"question_text": "Nested loops execute how?", "options": ["The outer loop completes all iterations before the inner loop starts", "The inner loop completes all of its iterations for every single iteration of the outer loop", "They execute in parallel asynchronously", "The inner loop executes once per outer loop iteration"], "correct_answer": "The inner loop completes all of its iterations for every single iteration of the outer loop", "explanation": "For every tick of the outer loop, the inner loop fires up and completes its entire cycle.", "difficulty": "Medium"}
    ],
    6: [
        {"question_text": "What is a function prototype?", "options": ["The actual code block of the function", "A declaration that tells the compiler the function's name, return type, and parameters before its full definition", "A macro defined by the preprocessor", "A function that returns no value"], "correct_answer": "A declaration that tells the compiler the function's name, return type, and parameters before its full definition", "explanation": "A prototype (e.g., `int add(int a, int b);`) allows the compiler to verify calls to the function before encountering its actual body.", "difficulty": "Beginner"},
        {"question_text": "What does a 'void' return type mean?", "options": ["The function returns an integer 0", "The function returns a null pointer", "The function does not return any value to the caller", "The function takes no arguments"], "correct_answer": "The function does not return any value to the caller", "explanation": "Using void as the return type specifies that the function performs an action but yields no data back.", "difficulty": "Beginner"},
        {"question_text": "What is the CPU call stack?", "options": ["A data structure that tracks memory allocations on the heap", "A memory region that manages active function calls, pushing a stack frame for each call and popping it upon return", "A global variable storage area", "A queue used for thread synchronization"], "correct_answer": "A memory region that manages active function calls, pushing a stack frame for each call and popping it upon return", "explanation": "The call stack tracks execution flow. When a function is called, its local variables and return address are pushed onto the stack.", "difficulty": "Medium"},
        {"question_text": "What is recursion?", "options": ["A loop that never ends", "A function that calls itself to solve smaller instances of the same problem", "A function that takes another function as an argument", "A process that frees dynamic memory"], "correct_answer": "A function that calls itself to solve smaller instances of the same problem", "explanation": "Recursion involves a function repeatedly calling itself until it reaches a defined base case.", "difficulty": "Beginner"},
        {"question_text": "What happens if a recursive function lacks a valid base case?", "options": ["The compiler automatically adds one", "It runs identically to a while loop", "It creates infinite recursive calls, eventually causing a Stack Overflow crash", "It returns 0 by default"], "correct_answer": "It creates infinite recursive calls, eventually causing a Stack Overflow crash", "explanation": "Without a base case, the stack continues to grow with new function frames until memory is exhausted.", "difficulty": "Medium"},
        {"question_text": "In C, parameters are passed to functions by:", "options": ["Value, meaning copies of the variables are sent", "Reference, meaning original variables are always modified", "Global scope projection", "Pointer delegation only"], "correct_answer": "Value, meaning copies of the variables are sent", "explanation": "C natively passes arguments by value. To modify original variables, developers must explicitly pass pointers (simulate pass-by-reference).", "difficulty": "Hard"},
        {"question_text": "What is a local variable?", "options": ["A variable accessible from any file in the project", "A variable accessible anywhere within the same C file", "A variable declared inside a function or block, accessible only within that block", "A variable stored in the heap"], "correct_answer": "A variable declared inside a function or block, accessible only within that block", "explanation": "Local variables exist only within their declaring block and are destroyed when the block (e.g., function) exits.", "difficulty": "Beginner"},
        {"question_text": "What is the purpose of the 'return' statement?", "options": ["To print output to the console", "To allocate memory", "To exit the function immediately and optionally send a value back to the caller", "To restart the function"], "correct_answer": "To exit the function immediately and optionally send a value back to the caller", "explanation": "Return passes execution control (and a calculated value) back to the calling function, terminating the current function.", "difficulty": "Beginner"}
    ],
    7: [
        {"question_text": "How are array elements indexed in C?", "options": ["Starting from 1", "Starting from 0", "Starting from -1", "Using alphabetical characters"], "correct_answer": "Starting from 0", "explanation": "C uses zero-based indexing, meaning the first element is at index 0, representing a zero offset from the array's memory address.", "difficulty": "Beginner"},
        {"question_text": "How is a 2D array arranged in physical RAM?", "options": ["Column-major order", "Fragmented across the heap", "Row-major order (all elements of row 0 are contiguous, followed immediately by row 1)", "As an array of pointers"], "correct_answer": "Row-major order (all elements of row 0 are contiguous, followed immediately by row 1)", "explanation": "C flattens multidimensional arrays into a single contiguous block of memory row by row.", "difficulty": "Medium"},
        {"question_text": "What happens if you access an array out of bounds (e.g., arr[10] on a 5-element array)?", "options": ["The compiler blocks compilation", "The program gracefully returns 0", "Undefined behavior, potentially corrupting adjacent memory or causing a segmentation fault", "The array automatically expands"], "correct_answer": "Undefined behavior, potentially corrupting adjacent memory or causing a segmentation fault", "explanation": "C does not perform bounds checking. Accessing out of bounds reads/writes raw memory belonging to other variables or secure areas.", "difficulty": "Hard"},
        {"question_text": "If you initialize an array partially: `int arr[5] = {1, 2};`, what happens to the remaining elements?", "options": ["They contain random garbage values", "They are automatically initialized to 0", "It causes a compilation error", "They are initialized to NULL"], "correct_answer": "They are automatically initialized to 0", "explanation": "If an array is partially initialized at declaration, the C standard guarantees the remaining elements are set to zero.", "difficulty": "Medium"},
        {"question_text": "Can you assign one array to another directly using the assignment operator (arr1 = arr2)?", "options": ["Yes, it performs a deep copy", "Yes, it performs a shallow copy", "No, array names are constant pointers and cannot be reassigned; you must copy element-by-element or use memcpy", "No, arrays can only be passed to functions"], "correct_answer": "No, array names are constant pointers and cannot be reassigned; you must copy element-by-element or use memcpy", "explanation": "C does not support direct array assignment. You must manually copy the bytes or iterate over the elements.", "difficulty": "Hard"},
        {"question_text": "How do you calculate the total byte size of an array in memory?", "options": ["sizeof(arr)", "length(arr)", "count(arr)", "arr.size()"], "correct_answer": "sizeof(arr)", "explanation": "The sizeof operator returns the total number of bytes allocated for the array in the current scope.", "difficulty": "Beginner"},
        {"question_text": "How do you determine the number of elements in an array?", "options": ["sizeof(arr)", "sizeof(arr) / sizeof(arr[0])", "length(arr)", "size(arr)"], "correct_answer": "sizeof(arr) / sizeof(arr[0])", "explanation": "Dividing the total array byte size by the byte size of a single element yields the element count.", "difficulty": "Medium"},
        {"question_text": "When an array is passed to a function, what is actually passed?", "options": ["A full copy of the array data", "A pointer to the first element of the array", "The size of the array", "A reference object"], "correct_answer": "A pointer to the first element of the array", "explanation": "Arrays decay into pointers when passed to functions, meaning the function receives the memory address, not a copy of the data.", "difficulty": "Hard"}
    ]
}

def inject_quizzes():
    file_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'content_c.py')
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    for module_num, new_questions in QUIZZES.items():
        var_name = f"m{module_num}_quizzes"
        pattern = rf"(\b{var_name}\s*=\s*\[.*?\n    \])"
        match = re.search(pattern, content, flags=re.DOTALL)
        if not match:
            print(f"Could not find {var_name}")
            continue
            
        original_block = match.group(1)
        new_items_str = ""
        for q in new_questions:
            new_items_str += ",\n        {\n"
            new_items_str += f"            \"question_text\": \"{q['question_text']}\",\n"
            opt_str = ", ".join([f'"{o}"' for o in q['options']])
            new_items_str += f"            \"options\": [{opt_str}],\n"
            new_items_str += f"            \"correct_answer\": \"{q['correct_answer']}\",\n"
            new_items_str += f"            \"explanation\": \"{q['explanation']}\",\n"
            new_items_str += f"            \"difficulty\": \"{q['difficulty']}\"\n"
            new_items_str += "        }"
            
        insertion_point = original_block.rfind(']')
        if insertion_point != -1:
            modified_block = original_block[:insertion_point] + new_items_str + "\n    " + original_block[insertion_point:]
            content = content.replace(original_block, modified_block)

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print("Injected part 1 quizzes into content_c.py successfully.")

if __name__ == '__main__':
    inject_quizzes()
