import os
import re

QUIZZES = {
    8: [
        {"question_text": "In C, how is a string represented in memory?", "options": ["As a dedicated String primitive type", "As a linked list of characters", "As a contiguous array of characters terminated by a null character ('\\0')", "As a struct containing a char array and a length integer"], "correct_answer": "As a contiguous array of characters terminated by a null character ('\\0')", "explanation": "C strings are simply character arrays. The null terminator '\\0' is critical for string functions to know where the text ends.", "difficulty": "Beginner"},
        {"question_text": "What is the ASCII value of the null terminator '\\0'?", "options": ["32 (space)", "48 (zero)", "0", "255"], "correct_answer": "0", "explanation": "The null terminator is the ASCII character with a numeric value of exactly 0.", "difficulty": "Beginner"},
        {"question_text": "Which standard library function calculates the length of a string?", "options": ["strsize()", "length()", "strlen()", "strcnt()"], "correct_answer": "strlen()", "explanation": "strlen() counts characters in a string up to, but not including, the null terminator.", "difficulty": "Beginner"},
        {"question_text": "Does strlen() include the null terminator in its count?", "options": ["Yes", "No", "Only for dynamic strings", "Depends on the compiler"], "correct_answer": "No", "explanation": "strlen() returns the number of visible characters. The null terminator is strictly a boundary marker.", "difficulty": "Medium"},
        {"question_text": "Which function safely concatenates two strings, preventing buffer overflows?", "options": ["strcat()", "strncat()", "append()", "concat()"], "correct_answer": "strncat()", "explanation": "strncat() accepts a length limit parameter, ensuring it won't write beyond the destination buffer's capacity.", "difficulty": "Medium"},
        {"question_text": "What does strcmp(\"apple\", \"banana\") return?", "options": ["0", "A positive integer", "A negative integer", "True"], "correct_answer": "A negative integer", "explanation": "strcmp returns a negative value because 'a' has a lower ASCII value than 'b', meaning 'apple' comes first alphabetically.", "difficulty": "Hard"},
        {"question_text": "What happens if a string lacks a null terminator and you call printf(\"%s\") on it?", "options": ["printf automatically stops after 10 characters", "printf throws a compile error", "printf continues reading memory past the array bounds until it randomly hits a zero byte, causing garbage output or a crash", "printf prints nothing"], "correct_answer": "printf continues reading memory past the array bounds until it randomly hits a zero byte, causing garbage output or a crash", "explanation": "Functions relying on %s trust the null terminator to stop reading memory. Without it, they read blindly out of bounds.", "difficulty": "Hard"},
        {"question_text": "If char name[5] = \"Hello\"; what is the vulnerability here?", "options": ["None, it is perfectly valid", "The array is too small to hold the null terminator, causing a buffer overflow", "The string is not capitalized", "name is a reserved keyword"], "correct_answer": "The array is too small to hold the null terminator, causing a buffer overflow", "explanation": "\"Hello\" requires 6 bytes (5 for letters + 1 for '\\0'). Providing only 5 bytes means no terminator is stored.", "difficulty": "Hard"}
    ],
    9: [
        {"question_text": "What does a pointer variable store?", "options": ["An integer value", "A floating-point value", "The RAM memory address of another variable", "A string constant"], "correct_answer": "The RAM memory address of another variable", "explanation": "Pointers are specialized variables designed exclusively to hold physical or virtual memory addresses.", "difficulty": "Beginner"},
        {"question_text": "Which operator is used to get the memory address of a variable?", "options": ["* (Dereference)", "& (Address-of)", "% (Modulo)", "-> (Arrow)"], "correct_answer": "& (Address-of)", "explanation": "The & operator retrieves the memory address of a variable, e.g., &val yields the address where val lives.", "difficulty": "Beginner"},
        {"question_text": "What does the dereference operator (*) do?", "options": ["Multiplies two pointers together", "Retrieves or modifies the value stored at the memory address the pointer holds", "Frees the memory", "Checks if a pointer is NULL"], "correct_answer": "Retrieves or modifies the value stored at the memory address the pointer holds", "explanation": "Dereferencing a pointer follows the address to access the actual data living at that location in RAM.", "difficulty": "Medium"},
        {"question_text": "What is a NULL pointer?", "options": ["A pointer that points to address 0, explicitly indicating it points to nothing valid", "A pointer that points to a string of zeroes", "A pointer that has been freed", "A pointer that points to negative memory"], "correct_answer": "A pointer that points to address 0, explicitly indicating it points to nothing valid", "explanation": "Setting a pointer to NULL is a universally recognized way to flag that the pointer is uninitialized or empty.", "difficulty": "Medium"},
        {"question_text": "If `int x = 5; int *p = &x; *p = 10;`, what is the value of x?", "options": ["5", "10", "Undefined", "0"], "correct_answer": "10", "explanation": "Dereferencing p (*p = 10) directly reaches into x's memory address and overwrites its value with 10.", "difficulty": "Hard"},
        {"question_text": "What happens if you dereference an uninitialized pointer (e.g., int *p; *p = 5;)?", "options": ["The compiler automatically allocates memory", "The program safely ignores it", "The program writes to a random memory address, usually resulting in a Segmentation Fault (crash)", "The pointer automatically becomes NULL"], "correct_answer": "The program writes to a random memory address, usually resulting in a Segmentation Fault (crash)", "explanation": "An uninitialized pointer holds a garbage address. Dereferencing it attempts to corrupt unknown memory, causing a crash.", "difficulty": "Hard"},
        {"question_text": "Why must pointers be declared with a specific data type (e.g., int * instead of just pointer p)?", "options": ["To make the code look organized", "Because the compiler needs to know how many bytes to read/write when dereferencing the pointer", "Because pointers can only point to integers", "So the pointer itself takes up more memory"], "correct_answer": "Because the compiler needs to know how many bytes to read/write when dereferencing the pointer", "explanation": "An address is just a starting point. The type tells the compiler how many bytes to fetch (e.g., 4 bytes for int, 8 for double).", "difficulty": "Hard"},
        {"question_text": "What does a double pointer (e.g., int **) hold?", "options": ["A pointer to an 8-byte double", "Two memory addresses at once", "The memory address of another pointer variable", "A 2D array matrix"], "correct_answer": "The memory address of another pointer variable", "explanation": "A double pointer holds the address of a pointer. This allows functions to modify the address that the target pointer holds.", "difficulty": "Hard"}
    ],
    10: [
        {"question_text": "What does the expression `arr` evaluate to when passed to a function?", "options": ["The total size of the array", "A copy of all array elements", "A pointer to the first element (&arr[0])", "The value of the first element"], "correct_answer": "A pointer to the first element (&arr[0])", "explanation": "Array names decay into pointers to their 0th element, which is why passing arrays doesn't copy data.", "difficulty": "Beginner"},
        {"question_text": "If `int *p` points to an integer array, what does `p + 1` do?", "options": ["Adds 1 to the integer value", "Increments the memory address by 1 byte", "Increments the memory address by sizeof(int) bytes", "Moves the pointer to the end of the array"], "correct_answer": "Increments the memory address by sizeof(int) bytes", "explanation": "Pointer arithmetic is scaled by the data type. Adding 1 to an int pointer skips forward exactly one int (usually 4 bytes).", "difficulty": "Medium"},
        {"question_text": "How is `arr[i]` interpreted by the C compiler?", "options": ["As a strict bounds-checked lookup", "As a function call", "Exactly as `*(arr + i)`", "As a macro expansion"], "correct_answer": "Exactly as `*(arr + i)`", "explanation": "The array indexing syntax is literally just syntactic sugar for pointer arithmetic and dereferencing.", "difficulty": "Medium"},
        {"question_text": "Can you increment an array name (e.g., `arr++`)?", "options": ["Yes, it moves to the next element", "No, array names act as constant pointers that cannot be reassigned", "Only if the array is dynamic", "Only inside a loop"], "correct_answer": "No, array names act as constant pointers that cannot be reassigned", "explanation": "While `arr` yields an address, it is not a modifiable variable holding an address; you cannot change where `arr` points.", "difficulty": "Hard"},
        {"question_text": "What is the difference between `char *str = \"Hello\";` and `char arr[] = \"Hello\";`?", "options": ["They are identical", "str points to read-only memory; arr is a modifiable copy on the stack", "str is a stack array; arr is read-only", "arr requires malloc"], "correct_answer": "str points to read-only memory; arr is a modifiable copy on the stack", "explanation": "String literals are stored in read-only memory. `char *str` points directly there. `char arr[]` copies the literal onto the modifiable stack.", "difficulty": "Hard"},
        {"question_text": "If `int arr[5];`, what does `sizeof(arr)` evaluate to?", "options": ["4 or 8 (size of a pointer)", "5", "5 * sizeof(int) (usually 20 bytes)", "0"], "correct_answer": "5 * sizeof(int) (usually 20 bytes)", "explanation": "Unlike pointer decay in function calls, calling sizeof directly on an array name in its declaring scope yields the total byte size of the array.", "difficulty": "Hard"},
        {"question_text": "When a function signature specifies `void process(int arr[])`, what is the actual type of `arr`?", "options": ["A full array structure", "A constant array", "A pointer `int *arr`", "A double pointer"], "correct_answer": "A pointer `int *arr`", "explanation": "In function parameters, array syntax `int arr[]` is secretly converted to pointer syntax `int *arr` by the compiler.", "difficulty": "Medium"},
        {"question_text": "What happens if you subtract two pointers pointing to the same array?", "options": ["It causes a syntax error", "It yields the difference in raw bytes", "It yields the number of elements between them (pointer distance)", "It yields the sum of their values"], "correct_answer": "It yields the number of elements between them (pointer distance)", "explanation": "Pointer subtraction is automatically divided by the element size, giving the logical distance in elements.", "difficulty": "Hard"}
    ],
    11: [
        {"question_text": "What is the purpose of a 'struct' in C?", "options": ["To create an array of identical types", "To group related variables of different data types under a single name", "To create a loop", "To declare global constants"], "correct_answer": "To group related variables of different data types under a single name", "explanation": "Structs allow developers to build complex composite data types representing real-world objects.", "difficulty": "Beginner"},
        {"question_text": "How do you access a member 'age' of a struct instance 'person'?", "options": ["person->age", "person.age", "person::age", "person[age]"], "correct_answer": "person.age", "explanation": "The dot operator (.) is used to access fields of a direct struct variable.", "difficulty": "Beginner"},
        {"question_text": "If you have a pointer to a struct (`struct Person *ptr`), how do you access the 'age' member?", "options": ["ptr.age", "*ptr.age", "ptr->age", "ptr::age"], "correct_answer": "ptr->age", "explanation": "The arrow operator (->) is required when accessing members through a pointer, replacing (*ptr).age.", "difficulty": "Medium"},
        {"question_text": "What is 'padding' in the context of C structures?", "options": ["Empty space inserted by the compiler between struct members to align them for faster CPU memory access", "A security feature to prevent buffer overflows", "Extra memory allocated at the end of a struct for dynamic arrays", "Whitespace in the source code"], "correct_answer": "Empty space inserted by the compiler between struct members to align them for faster CPU memory access", "explanation": "CPUs fetch memory faster when it aligns with hardware word boundaries (e.g., 4 or 8 bytes). Compilers pad structs to ensure this alignment.", "difficulty": "Hard"},
        {"question_text": "How does a 'union' fundamentally differ from a 'struct'?", "options": ["A union cannot contain integers", "A union allocates memory for all its fields simultaneously", "All members of a union share the exact same memory location, meaning it can only hold one active value at a time", "A union is only used for networking"], "correct_answer": "All members of a union share the exact same memory location, meaning it can only hold one active value at a time", "explanation": "Unions overlay their fields in memory. Overwriting one field destroys the data in the other fields.", "difficulty": "Medium"},
        {"question_text": "What is the primary use case for the 'typedef' keyword?", "options": ["To define macros", "To allocate memory", "To create an alias for an existing data type to simplify complex declarations", "To include header files"], "correct_answer": "To create an alias for an existing data type to simplify complex declarations", "explanation": "typedef allows you to alias complex struct declarations so you don't have to repeat the 'struct' keyword everywhere.", "difficulty": "Medium"},
        {"question_text": "What does an 'enum' (enumeration) do?", "options": ["Assigns custom string values to variables", "Defines a set of named integer constants for better code readability", "Allocates a dynamic array", "Parses user input"], "correct_answer": "Defines a set of named integer constants for better code readability", "explanation": "Enums map readable names (like STATE_RUNNING) to integers (like 0, 1, 2) to replace hardcoded numbers.", "difficulty": "Beginner"},
        {"question_text": "If a struct contains a char (1 byte) and an int (4 bytes), what is its typical size on a 32-bit system due to padding?", "options": ["5 bytes", "6 bytes", "8 bytes", "4 bytes"], "correct_answer": "8 bytes", "explanation": "The char uses 1 byte, followed by 3 bytes of padding, followed by the 4-byte int, totaling 8 bytes.", "difficulty": "Hard"}
    ],
    12: [
        {"question_text": "Which memory segment grows dynamically as the program requests memory at runtime?", "options": ["The Stack", "The BSS Segment", "The Heap", "The Code/Text Segment"], "correct_answer": "The Heap", "explanation": "The heap is used for dynamic memory allocation (malloc), while the stack handles automatic local variables.", "difficulty": "Beginner"},
        {"question_text": "What does the malloc() function do?", "options": ["Initializes memory to zero", "Allocates a requested number of uninitialized bytes on the heap and returns a pointer to it", "Frees memory", "Resizes an array on the stack"], "correct_answer": "Allocates a requested number of uninitialized bytes on the heap and returns a pointer to it", "explanation": "malloc (memory allocation) grabs raw heap memory. The developer is responsible for tracking and freeing it.", "difficulty": "Medium"},
        {"question_text": "How does calloc() differ from malloc()?", "options": ["calloc allocates on the stack", "calloc is faster", "calloc automatically initializes the allocated memory bytes to zero", "calloc automatically frees memory"], "correct_answer": "calloc automatically initializes the allocated memory bytes to zero", "explanation": "While malloc leaves memory with garbage values, calloc wipes the memory clean to zeros before returning it.", "difficulty": "Medium"},
        {"question_text": "What is a memory leak?", "options": ["A hardware failure in RAM", "A situation where dynamically allocated heap memory is never freed, exhausting available RAM", "A buffer overflow that overwrites other variables", "A null pointer dereference"], "correct_answer": "A situation where dynamically allocated heap memory is never freed, exhausting available RAM", "explanation": "Losing the pointer to heap memory without calling free() creates an unrecoverable leak until the OS kills the process.", "difficulty": "Hard"},
        {"question_text": "What is the purpose of the realloc() function?", "options": ["To free memory", "To initialize memory", "To resize a previously allocated block of heap memory, preserving its existing contents", "To copy memory from stack to heap"], "correct_answer": "To resize a previously allocated block of heap memory, preserving its existing contents", "explanation": "realloc requests a larger (or smaller) memory block. If it has to move the data to a new location, it copies it automatically.", "difficulty": "Hard"},
        {"question_text": "What does malloc() return if the system is completely out of RAM?", "options": ["A random address", "The program crashes immediately", "It returns a NULL pointer", "It waits until memory is available"], "correct_answer": "It returns a NULL pointer", "explanation": "Malloc fails gracefully by returning NULL. Developers must check for NULL before using the pointer.", "difficulty": "Medium"},
        {"question_text": "What is a 'dangling pointer'?", "options": ["A pointer that holds the address of memory that has already been freed", "A pointer that points to a string", "A pointer initialized to NULL", "A pointer to a function"], "correct_answer": "A pointer that holds the address of memory that has already been freed", "explanation": "Accessing a dangling pointer (use-after-free) causes undefined behavior because the memory might have been reassigned to something else.", "difficulty": "Hard"},
        {"question_text": "Why should you set a pointer to NULL immediately after calling free(p)?", "options": ["To free the memory twice", "To trigger garbage collection", "To prevent dangling pointer bugs by ensuring accidental dereferences safely crash rather than corrupting memory", "To save memory space"], "correct_answer": "To prevent dangling pointer bugs by ensuring accidental dereferences safely crash rather than corrupting memory", "explanation": "Setting it to NULL turns a dangerous silent corruption bug into an immediate, easy-to-detect crash.", "difficulty": "Hard"}
    ],
    13: [
        {"question_text": "What data type is used as a handle for file operations in C?", "options": ["int", "FILE *", "char *", "struct File"], "correct_answer": "FILE *", "explanation": "The FILE structure pointer represents an I/O stream, tracking buffers, file position indicators, and errors.", "difficulty": "Beginner"},
        {"question_text": "Which function opens a file in C?", "options": ["open()", "read()", "fopen()", "file_open()"], "correct_answer": "fopen()", "explanation": "fopen() bridges the program to the OS file system, returning a FILE pointer.", "difficulty": "Beginner"},
        {"question_text": "What happens if you open a file in 'w' (write) mode and the file already exists?", "options": ["An error is returned", "Data is appended to the end of the file", "The file's existing contents are immediately truncated (erased)", "The program crashes"], "correct_answer": "The file's existing contents are immediately truncated (erased)", "explanation": "Write mode ('w') destroys existing data. To preserve data, append mode ('a') must be used.", "difficulty": "Medium"},
        {"question_text": "Which mode should be used to read a binary file (like an image)?", "options": ["'r'", "'rb'", "'w'", "'wb'"], "correct_answer": "'rb'", "explanation": "'rb' specifies read-binary, preventing the OS from interpreting newline characters differently (crucial on Windows).", "difficulty": "Medium"},
        {"question_text": "Why is it strictly necessary to call fclose() when finished with a file?", "options": ["To prevent memory leaks and ensure I/O buffers are flushed to the disk", "To format the disk", "To compile the file", "To convert the file to a string"], "correct_answer": "To prevent memory leaks and ensure I/O buffers are flushed to the disk", "explanation": "fclose() writes pending buffered data to the physical disk and releases OS file locks.", "difficulty": "Hard"},
        {"question_text": "Which function reads a formatted string from a file, similar to scanf?", "options": ["fprintf()", "fscanf()", "fgets()", "fread()"], "correct_answer": "fscanf()", "explanation": "fscanf() parses data from a FILE stream using format specifiers like %d and %s.", "difficulty": "Medium"},
        {"question_text": "What function is used for bulk reading raw binary data structures from a file?", "options": ["fgets()", "fgetc()", "fread()", "fscanf()"], "correct_answer": "fread()", "explanation": "fread() reads a specified number of bytes directly into a memory buffer without formatting.", "difficulty": "Hard"},
        {"question_text": "What does EOF signify in file processing?", "options": ["End Of File – a macro indicating no more data can be read from the stream", "Error On File – a disk hardware failure", "Execute Object File – running a binary", "End Of Formatting"], "correct_answer": "End Of File – a macro indicating no more data can be read from the stream", "explanation": "EOF (usually -1) is returned by reading functions when the file pointer reaches the end of the file.", "difficulty": "Beginner"}
    ],
    14: [
        {"question_text": "When are preprocessor directives (like #define) executed?", "options": ["During execution", "During linking", "Before the code is translated into assembly language by the compiler", "During runtime memory allocation"], "correct_answer": "Before the code is translated into assembly language by the compiler", "explanation": "The preprocessor scans the source code, expanding macros and including files, creating a pure C file for the compiler.", "difficulty": "Medium"},
        {"question_text": "What is the primary danger of using #define macros instead of functions?", "options": ["They are slower to execute", "They use more RAM", "They lack type checking and can cause unexpected side effects if arguments are evaluated multiple times (e.g., MAX(i++, j))", "They cannot return values"], "correct_answer": "They lack type checking and can cause unexpected side effects if arguments are evaluated multiple times (e.g., MAX(i++, j))", "explanation": "Macros are literal text substitutions. Passing an increment operation can result in the increment happening twice.", "difficulty": "Hard"},
        {"question_text": "What is the purpose of #ifndef in a header file?", "options": ["To define a variable", "To include a library", "To prevent a header file from being included multiple times (header guards)", "To link an object file"], "correct_answer": "To prevent a header file from being included multiple times (header guards)", "explanation": "Include guards prevent compiler errors caused by redefining structs or macros when a header is included multiple times.", "difficulty": "Hard"},
        {"question_text": "What is the difference between #include <file.h> and #include \"file.h\"?", "options": ["<file.h> is for C, \"file.h\" is for C++", "They are identical", "<file.h> searches standard system directories, \"file.h\" searches the local directory first", "The first is a macro, the second is a function"], "correct_answer": "<file.h> searches standard system directories, \"file.h\" searches the local directory first", "explanation": "Angle brackets are used for standard libraries, quotes are used for project-local header files.", "difficulty": "Medium"},
        {"question_text": "What is conditional compilation?", "options": ["Compiling only if the user types a password", "Using #ifdef and #endif to include or exclude blocks of code during preprocessing (e.g., for debug vs release builds)", "Compiling code in a loop", "Executing code depending on a runtime if statement"], "correct_answer": "Using #ifdef and #endif to include or exclude blocks of code during preprocessing (e.g., for debug vs release builds)", "explanation": "Conditional compilation physically removes code blocks from the source file before the compiler sees them based on macros.", "difficulty": "Hard"},
        {"question_text": "Can a #define macro contain multiple lines of code?", "options": ["No, it is strictly one line", "Yes, by using the backslash (\\) line continuation character", "Yes, by enclosing it in {}", "Yes, using semicolons"], "correct_answer": "Yes, by using the backslash (\\) line continuation character", "explanation": "The backslash escapes the newline, allowing the preprocessor to treat multi-line code as a single logical line.", "difficulty": "Medium"},
        {"question_text": "What is a variadic macro?", "options": ["A macro that takes no arguments", "A macro that takes a variable number of arguments using ... and __VA_ARGS__", "A macro used for variables", "A macro that changes its return type"], "correct_answer": "A macro that takes a variable number of arguments using ... and __VA_ARGS__", "explanation": "Variadic macros are highly useful for custom logging wrappers that wrap printf.", "difficulty": "Hard"},
        {"question_text": "How do you permanently undefine a macro during preprocessing?", "options": ["#delete", "#remove", "#undef", "#clear"], "correct_answer": "#undef", "explanation": "#undef removes a previously defined macro, allowing you to redefine it differently further down the file.", "difficulty": "Beginner"}
    ],
    15: [
        {"question_text": "What does a Segmentation Fault signify?", "options": ["A syntax error", "The program tried to access a restricted or invalid memory address (e.g., dereferencing NULL)", "The program ran out of disk space", "A math division by zero error"], "correct_answer": "The program tried to access a restricted or invalid memory address (e.g., dereferencing NULL)", "explanation": "The OS triggers a SegFault when a process violates memory protection rules, killing the process instantly.", "difficulty": "Medium"},
        {"question_text": "Which tool is commonly used on Linux to debug Segmentation Faults and memory leaks?", "options": ["gcc", "make", "Valgrind", "nano"], "correct_answer": "Valgrind", "explanation": "Valgrind instruments the executable, tracking every memory allocation and memory access to pinpoint leaks and illegal reads.", "difficulty": "Hard"},
        {"question_text": "What is gdb?", "options": ["A text editor", "The GNU Debugger, used for stepping through code, setting breakpoints, and inspecting variables", "A compiler", "A memory allocator"], "correct_answer": "The GNU Debugger, used for stepping through code, setting breakpoints, and inspecting variables", "explanation": "GDB is the standard debugger for C, allowing developers to inspect process memory during live execution or post-crash (core dumps).", "difficulty": "Medium"},
        {"question_text": "In a Linked List data structure, what does each 'Node' contain?", "options": ["Only data", "Only a pointer", "Data and a pointer to the next Node in the sequence", "A pointer to a file stream"], "correct_answer": "Data and a pointer to the next Node in the sequence", "explanation": "Linked lists map disjointed heap memory blocks together using pointers, allowing dynamic resizing without contiguous memory.", "difficulty": "Hard"},
        {"question_text": "What is the primary advantage of a Linked List over a standard C Array?", "options": ["Linked lists have faster index lookups", "Linked lists use less memory", "Linked lists can easily grow dynamically and insert elements in O(1) time without shifting massive memory blocks", "Linked lists are built-in primitives"], "correct_answer": "Linked lists can easily grow dynamically and insert elements in O(1) time without shifting massive memory blocks", "explanation": "Arrays require contiguous memory and shifting to insert. Linked lists just rewire two pointers.", "difficulty": "Hard"},
        {"question_text": "What compiler flag is used in gcc to include debugging symbols for gdb?", "options": ["-O3", "-g", "-Wall", "-c"], "correct_answer": "-g", "explanation": "The -g flag embeds source code mappings into the binary so GDB can show human-readable variable names and lines.", "difficulty": "Medium"},
        {"question_text": "What is a 'core dump'?", "options": ["Deleting source code", "A snapshot of the program's working memory at the exact moment it crashed, used for post-mortem debugging", "A memory leak", "Clearing the cache"], "correct_answer": "A snapshot of the program's working memory at the exact moment it crashed, used for post-mortem debugging", "explanation": "Core dumps allow developers to load the crashed state into GDB and inspect exactly why a production server crashed.", "difficulty": "Hard"},
        {"question_text": "When building large projects, what tool automates the compilation of only the files that have changed?", "options": ["gcc", "gdb", "make (using a Makefile)", "git"], "correct_answer": "make (using a Makefile)", "explanation": "Make tracks file modification timestamps and only invokes the compiler on source files that have been updated, saving massive compilation time.", "difficulty": "Beginner"}
    ]
}

def inject_quizzes():
    file_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'content_c.py')
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    for module_num, new_questions in QUIZZES.items():
        var_name = f"m{module_num}_quizzes"
        pattern = rf"(\b{var_name}\s*=\s*\[.*?\n    \])"
        match = re.search(pattern, content, flags=re.DOTALL)
        if not match:
            print(f"Could not find {var_name}")
            continue
            
        original_block = match.group(1)
        new_items_str = ""
        for q in new_questions:
            new_items_str += ",\n        {\n"
            new_items_str += f"            \"question_text\": \"{q['question_text']}\",\n"
            opt_str = ", ".join([f'"{o}"' for o in q['options']])
            new_items_str += f"            \"options\": [{opt_str}],\n"
            new_items_str += f"            \"correct_answer\": \"{q['correct_answer']}\",\n"
            new_items_str += f"            \"explanation\": \"{q['explanation']}\",\n"
            new_items_str += f"            \"difficulty\": \"{q['difficulty']}\"\n"
            new_items_str += "        }"
            
        insertion_point = original_block.rfind(']')
        if insertion_point != -1:
            modified_block = original_block[:insertion_point] + new_items_str + "\n    " + original_block[insertion_point:]
            content = content.replace(original_block, modified_block)

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print("Injected part 2 quizzes into content_c.py successfully.")

if __name__ == '__main__':
    inject_quizzes()
